export enum PpqOtherFactorsEnum {
  HAS_SENSITIVE_PERSONAL_INFORMATION = 'HAS_SENSITIVE_PERSONAL_INFORMATION',
  HAS_SHARING_OF_PERSONAL_INFORMATION = 'HAS_SHARING_OF_PERSONAL_INFORMATION',
  HAS_PROGRAM_AGREEMENT = 'HAS_PROGRAM_AGREEMENT',
  HAS_OTHERS_ACCESS_TO_PERSONAL_INFORNATION = 'HAS_OTHERS_ACCESS_TO_PERSONAL_INFORNATION',
  HAS_CLOUD_TECHNOLOGY = 'HAS_CLOUD_TECHNOLOGY',
  HAS_POTENTIAL_PUBLIC_INTEREST = 'HAS_POTENTIAL_PUBLIC_INTEREST',
  HAS_DISCLOSURE_OUTSIDE_OF_CANADA = 'HAS_DISCLOSURE_OUTSIDE_OF_CANADA',
  HAS_HIGH_VOLUMES_PERSONAL_INFORMATION = 'HAS_HIGH_VOLUMES_PERSONAL_INFORMATION',
  HAS_DATA_LINKING = 'HAS_DATA_LINKING',
  HAS_BC_SERVICES_CARD_ONBOARDING = 'HAS_BC_SERVICES_CARD_ONBOARDING',
  HAS_AI_OR_ML = 'HAS_AI_OR_ML',
  HAS_PARTNERSHIP_NON_MINISTRY = 'HAS_PARTNERSHIP_NON_MINISTRY',
}
