version: "3.7"
services:
  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  dpia-api:
    container_name: dpia-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    networks:
      - dpia-network
    ports:
      - "3000:3000"
  
  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  dpia-webapp:
    container_name: dpia-webapp
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    networks:
      - dpia-network
    ports:
      - "8080:8080"
  
networks:
  dpia-network: 
    driver: "bridge"
