version: "3.7"
services:
  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  dpia-api:
    container_name: dpia-api
    build:
      context: ./src/backend
      dockerfile: .docker/Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    networks:
      - dpia-network
    ports:
      - "3000:3000"
  
  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  dpia-webapp:
    container_name: dpia-webapp
    build:
      context: ./src/frontend
      dockerfile: .docker/Dockerfile
    networks:
      - dpia-network
    ports:
      - "8080:8080"
    tty: true
  
networks:
  dpia-network: 
    driver: "bridge"
