FROM node:18.9-alpine as build

WORKDIR /app

# creating diff
RUN apk update
RUN apk add curl

# Copy in build artifacts, build project dependencies

COPY package*.json ./

RUN npm install

COPY . .
EXPOSE 8080
CMD ["npm", "run", "dev"]
