FROM node:20.5-bullseye-slim as build

WORKDIR /app

# creating diff
RUN apt-get update && apt-get install -y curl

# Copy in build artifacts, build project dependencies

COPY package*.json ./

RUN npm install

COPY . .
EXPOSE 8080
CMD ["npm", "run", "dev"]
