export enum PiaIntakeStatusEnum {
  DRAFTING_IN_PROGRESS = 'DRAFTING_IN_PROGRESS',
  EDIT_IN_PROGRESS = 'EDIT_IN_PROGRESS',
  MPO_REVIEW = 'MPO_REVIEW',
  CPO_REVIEW = 'CPO_REVIEW',
  FINAL_REVIEW = 'FINAL_REVIEW',
  PENDING_COMPLETION = 'PENDING_COMPLETION',
  COMPLETE = 'COMPLETE',
}
