export const API_ROUTES = {
  PPQ_FORM_SUBMISSION: 'api/ppq',
  PIA_INTAKE: '/api/pia-intake',
  KEYCLOAK_CALLBACK: 'api/auth/callback',
  KEYCLOAK_USER: '/api/auth/user',
  KEYCLOAK_LOGOUT: '/api/auth/keycloakLogout',
  KEYCLOAK_LOGIN: '/api/auth/keycloakLogin',
  KEYCLOAK_REFRESH_TOKEN: '/api/auth/refreshToken',
  PPQ_RESULT_DOWNLOAD: '/api/ppq/download/:id',
  PIA_INTAKE_RESULT_DOWNLOAD: '/api/pia-intake/download/:id',
  CONFIG_FILE: '/api/configuration',
  GET_PIA_INTAKE: '/api/pia-intake/:id',
  PATCH_PIA_INTAKE: '/api/pia-intake/:id',
  PIA_COMMENTS: '/api/comments',
  GET_COMMENTS_COUNT: '/api/comments/count',
  DELETE_COMMENT: '/api/comments/:id',
  GET_INVITE_CODE: '/api/invite',
};
