export const OtherFactor = [
  'Sensitive personal information',
  'Regular or systematic sharing of personal information',
  'Common or integrated program agreement',
  'Vendor or third-party access to personal information',
  'Cloud technology',
  'Potential public interest in the initiative',
  'Disclosure of personal information outside of Canada',
  'High volumes of personal information',
  'Data-linking',
  'BC Services Card Onboarding',
  'Artificial intelligence (AI) or machine learning',
  'Partnership with non-ministry public bodies or other organizations',
];
export const ContactUserName = [
  'David Malcolm',
  'Luke Dupuis',
  'Melissa Sexsmith',
  "Jennifer O'Neil",
  'Chris Mutadi',
  'Shawna Lynch',
  'Jeannie Longacre',
  'Michelle Gilbertson',
  'David Johnson',
  'Quinn Fletcher',
  'Elena Bersenev',
  'Tara Ralph',
  'Chris Mutadi',
  'Brent Grover',
];
export const MinistryList = [
  'Advanced Education and Skills Training',
  'Agriculture and Food',
  'Attorney General',
  'BC Public Service Agency',
  'Children and Family Development',
  "Citizens' Services",
  'Education and Child Care',
  'Energy, Mines and Low Carbon Innovation',
  'Environment and Climate Change Strategy',
  'Finance',
  'Forests',
  'Government Communications and Public Engagement',
  'Health',
  'Indigenous Relations and Reconciliation',
  'Jobs, Economic Recovery and Innovation',
  'Labour',
  'Land, Water and Resource Stewardship',
  'Liquor Distribution Branch',
  'Mental Health and Addictions',
  'Municipal Affairs',
  'Office of the Premier',
  'Public Safety and Solicitor General and Emergency B.C.',
  'Social Development and Poverty Reduction',
  'Tourism, Arts, Culture and Sport',
  'Transportation and Infrastructure',
];

export const PIATypes = [
  'New initiative',
  'Initiative update',
  'Corporate Checklist',
  'I’m not sure',
];
