#!/bin/bash

# script to tag an 

docker tag $ARTPROJ_PROJECT_URL/$ARTPROJ_REPOSITORY/$SOURCE_IMAGE_NAME:$SOURCE_IMAGE_TAG $ARTPROJ_PROJECT_URL/$ARTPROJ_REPOSITORY/$TARGET_IMAGE_NAME:$TARGET_IMAGE_TAG
