export default {
  branch: 'sdfsd',
  createdAt: new Date('2022-12-08T19:23:17.220Z'),
  dataElementsInvolved: 'sfdfs',
  drafterEmail: 'bing.gao@gov.bc.ca',
  drafterName: 'Bing',
  drafterTitle: 'officer',
  hasAddedPiToDataElements: 'Yes',
  id: 6,
  initiativeDescription: 'sdfsd',
  initiativeScope: 'sdfsd',
  leadEmail: 'will@freshworks.io',
  leadName: 'Will',
  leadTitle: 'Manager',
  ministry: 'AGRICULTURE_AND_FOOD',
  mpoEmail: 'kushal@freshworks.io',
  mpoName: 'Kushal',
  status: 'submitted',
  riskMitigation: 'fsdfs',
  title: 'cfds',
  updatedAt: new Date('2022-12-08T19:23:17.220Z'),
};
