apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}-template
labels:
  template: ${APPLICATION_NAME}-template
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}-service
    namespace: ${LICENSE_PLATE}-${ENVIRONMENT}
    labels:
      hash: latest
      template: ${APPLICATION_NAME}-template
    annotations:
      aviinfrasetting.ako.vmware.com/name: dataclass-low
      kubectl.kubernetes.io/last-applied-configuration: >
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"hash":"latest","template":"dpia-webapp-template"},"name":"dpia-webapp","namespace":"aa77ab-dev"},"spec":{"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"dpia-webapp"},"sessionAffinity":"None","type":"ClusterIP"}}
  spec:
    ipFamilies:
      - IPv4
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    internalTrafficPolicy: Cluster
    type: ClusterIP
    ipFamilyPolicy: SingleStack
    sessionAffinity: None
    selector:
      app: dpia-webapp
