apiVersion: ops.gov.bc.ca/v1alpha1
kind: SysdigTeam
metadata:
  name: b996e6-sysdigteam
  namespace: b996e6-tools
spec:
  team:
    description: The Sysdig Team for the OpenShift Project Set DPIA
    users:
    - name: brandon.bouchard@gov.bc.ca
      role: ROLE_TEAM_EDIT
    - name: braden.mitchell@gov.bc.ca
      role: ROLE_TEAM_STANDARD
    - name: peggy.king@gov.bc.ca
      role: ROLE_TEAM_READ
