name: "E2E Pull Request Lint"
on:
  pull_request:
    branches: [main]
    paths:
      - "src/e2e/**"
  workflow_dispatch:

jobs:
  App-lint:
    runs-on: ubuntu-latest

    steps:

      - name: Install project dependencies, run lint
        run: |
          cd src/e2e
          npm ci
          npm run lint
