name: DPIA Frontend - PROD Promotion

on:
  workflow_dispatch:

jobs:
  PROD-tag-dpia-app-image:
    environment: APP-Prod
    runs-on: ubuntu-latest
    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Openshift Silver Cluster
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: github-actions
          OPENSHIFT_NAMESPACE: b996e6-tools
        with: 
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT4_TOOLS_SA_PASSWORD }}
          namespace: b996e6-tools
            
      # Login to BC Gov Docker Image Repository
      - name: Login to Openshift Docker
        run : |
          docker login ${{ secrets.OPENSHIFT4_PUBLIC_IMAGE_REPOSITORY_BASE_URL }} -u ${{ secrets.OPENSHIFT4_TOOLS_SA_USERNAME }} -p ${{ secrets.OPENSHIFT4_TOOLS_SA_PASSWORD }}

      # Tag test image with prod to promote deployment
      - name: Update tag for Imagestream
        env:
          TOOLS_NAMESPACE: "${{ secrets.TOOLS_NAMESPACE }}"
          IMAGESTREAM_SOURCE: "app-test"
          IMAGESTREAM_DESTINATION: "app-prod"
        run: |
          ./.github/helpers/tag-imagestream.sh

      # Logout of Docker Openshift before Working in Artifactory
      - name: Docker Logout of Openshift Repository
        run: |
          docker logout ${{ secrets.OPENSHIFT4_PUBLIC_IMAGE_REPOSITORY_BASE_URL }}

      #Login to Artifactory
      - name: Docker Login to Artifactory
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ secrets.ARTPROJ_PROJECT_URL }}
          username: ${{ secrets.ARTPROJ_SA_USERNAME }}
          password: ${{ secrets.ARTPROJ_SA_PASSWORD }}

      #Tag dev image with test tag in ARTIFACTORY to promote deployment
      - name: Update tag for Artifactory
        env: 
          ARTPROJ_PROJECT_URL: "${{ secrets.ARTPROJ_PROJECT_URL }}"
          ARTPROJ_REPOSITORY: "daa7-dpia-image-repository"
          SOURCE_IMAGE_NAME: app-test
          SOURCE_IMAGE_TAG: latest
          TARGET_IMAGE_NAME: app-prod
          TARGET_IMAGE_TAG: latest
        run: |

          ./.github/helpers/tag-artifactory-image.sh

          docker images

  PROD-deploy:
    runs-on: ubuntu-latest
    environment: APP-Prod
    needs: [ PROD-tag-dpia-app-image ]
    steps:
    
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Login to Openshift Silver Cluster
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: github-actions
          OPENSHIFT_NAMESPACE: b996e6-prod
        with: 
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT4_PROD_SA_PASSWORD }}
          namespace: b996e6-prod


      # Use deploy helper script to process and apply DPIA APP Application template into PROD namespace
      - name: Process and Apply APP DeploymentConfig, Service, Route templates
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_PROD_NAMESPACE }}"
          APPLICATION_NAME: "${{ secrets.APPLICATION_NAME }}-v2"
          LICENSE_PLATE: "${{ secrets.LICENSE_PLATE }}"
          ENVIRONMENT: "${{ secrets.ENVIRONMENT }}"
          DC_TEMPLATE: "app-dc-template.yaml"
          SERVICE_TEMPLATE: "app-service-template.yaml"
          ROUTE_TEMPLATE: "app-route-template.yaml"
          DIR: "app/silver"
          IMAGESTREAM: "app-prod"
        run: |
          ./.github/helpers/deploy.sh

  PROD-health-check:
    runs-on: ubuntu-latest
    environment:
      name: APP-Prod
      url: https://pia.gov.bc.ca/
    needs: [ PROD-deploy ]
    steps:
    
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Login to Openshift Silver Cluster
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: github-actions
          OPENSHIFT_NAMESPACE: b996e6-prod
        with: 
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT4_PROD_SA_PASSWORD }}
          namespace: b996e6-prod
            
      # Use application health helper script to monitor readiness/liveness probe response post deployment  
      - name: Health Check PROD deployment
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_PROD_NAMESPACE }}"
          APPLICATION_NAME: "${{ secrets.APPLICATION_NAME }}-v2"
        run: |
          ./.github/helpers/application-health.sh

  PROD-cleanup:
    runs-on: ubuntu-latest
    environment: APP-Prod
    needs: [ Prod-health-check ]
    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Openshift Silver Cluster
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: github-actions
          OPENSHIFT_NAMESPACE: b996e6-prod
        with: 
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT4_PROD_SA_PASSWORD }}
          namespace: b996e6-prod

      # Use cleanup helper script to remove any leftover deployment pod objects from previous deployment
      - name: Cleanup previous deployment pod objects
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_PROD_NAMESPACE }}"
        run: |
          ./.github/helpers/cleanup-pods.sh

      # Use cleanup helper script to remove any leftover deployment pod objects from previous deployment
      - name: Cleanup previous replication controller objects
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_PROD_NAMESPACE }}"
        run: |
          ./.github/helpers/cleanup-rc.sh
  
  PROD-Success-Notify:
    runs-on: ubuntu-latest
    environment: APP-Prod
    needs: [ PROD-cleanup ]
    steps:
      - name: Message Teams Channel on Success
        run: |
          curl --location --request POST ${{ secrets.TEAMS_SUCCESS_URL }} \
          --header 'Content-Type: text/plain' \
          --data-raw '{
            "@context": "https://schema.org/extensions",
            "@type": "MessageCard",
            "themeColor": "0072C6",
            "title": "SUCCESS! WebApp Deployment to PIA ${{ secrets.ENVIRONMENT }} Environment has finished.",
            "text": "The PIA WebApp has been built and deployed to the ${{ secrets.ENVIRONMENT }} environment. \n\n The logs for the successful deployment can be found [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\n\n The changes for commit ${{ github.sha }} can be found [here](https://pia.gov.bc.ca).",
          }'

  PROD-Failure-Notify:
    runs-on: ubuntu-latest
    environment: APP-Prod
    if: failure()
    steps:
      - name: Message Teams Channel on Failure
        run: |
          curl --location --request POST ${{ secrets.TEAMS_FAILURE_URL }} \
          --header 'Content-Type: text/plain' \
          --data-raw '{
            "@context": "https://schema.org/extensions",
            "@type": "MessageCard",
            "themeColor": "0072C6",
            "title": "FAILURE! WebApp Deployment to the PIA ${{ secrets.ENVIRONMENT }} Environment has failed.",
            "text": "The PIA WebApp has NOT been built and deployed to the ${{ secrets.LICENSE_PLATE }} ${{ secrets.ENVIRONMENT }} environment.\n\n Please review the Github Action for this deployment (here)[${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}].",
          }'
